config/routes.rb
ScionSwap::Application.routes.draw do
  devise_for :user, :only => :sessions, :constraints => {:format => 'text/html'}
  devise_for :user, :skip => :sessions, :controllers => { :confirmations => 'devise_overrides/confirmations' }
  devise_scope :user do
    post '/user/auth_token', :to => 'users#auth_token'
    root :to => 'devise/sessions#new'
    get 'user/change_password', :to => 'users#change_password', :as => :change_password   
    get 'user/unsubscribe_activation', :to => 'users#unsubscribe_activation', :as => :unsubscribe_activation
    get 'user/deactivate_reminder_mail/:confirmation_token', :to => 'users#deactivate_reminder_mail', :as => :deactivate_reminder_mail
    
  end
  
  resource :user do
    collection do
      put :update_password

    end
  end

  # Member Routes
  resources :users, :except => [:destroy] do 
    collection do
      get :admin, :as => :admin_dashboard
      get :dashboard
      get :activate
      get :edit
      get :current
      get :members
    end
    member do
      post :resend_confirmation
      post :add_credits
    end
  end
  scope :via => :get do
    match 'search/browse', :to => 'search#browse', :as => :browse
    match 'search(/:location(/:dealership_id))', :to => 'search#index', :as => :search   
    match 'terms', :to => 'static#show', :as => :terms
    match 'privacy', :to => 'static#show', :as => :privacy
    match 'faq', :to => 'static#show', :as => :faq
    match 'help', :to => 'static#help', :as => :help
  end

  resources :dealerships, :only => [:show, :edit, :update, :index] do
    resources :fleet_groups, :only => [:update] do
      resources :fleet_group_quantities, :only => [:index, :create, :destroy]
    end
    resources :dealership_holidays, :only => [:update, :create, :destroy]
    resources :reservations, :only => [:index]

    member do
      get :schedule
      get :inventory
      get :details
    end
  end

  resources :reservations, :except => [:destroy] do
    member do
      get :cancel
      put :cancel
      get :start
      put :start
      put :end
    end
  end
  
  resources :survey_questions, :controller => 'activation_survey_questions', :only => :index do
    resources :survey_answers, :controller => 'activation_survey_answers', :only => [:create, :index]
  end
  
  resources :activity_logs, :only => :index
end

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
  %nav.navbar-inner
    .container
      = link_to root_path, :class => 'brand', :target => '_self' do
        %strong SCION
        %i>SWAP&#160;
      %ul.nav.pull-right
        - if user_signed_in?
          %li
            = link_to 'Home', "/", :target => '_self'
          %li
            = link_to 'Account', edit_users_path, :target=> '_self'
          %li
            = link_to 'Logout', destroy_user_session_path, :method=>'delete'

app/views/layouts/application.html.haml
!!! 5
%html{:lang=>'en'}
  %head
    %title= content_for?(:title) ? yield(:title) : "Scion Swap"
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)

  %body{ng: {app: 'swap'}}
    #header
      = render 'layouts/header'

    #global-flash-messages.alerts{ng: {controller: 'FlashCtrl'}, ui: {show: 'flashMessages()'}}
      %div.alert{ng: {repeat: 'flash in flashMessages()', class: "{'alert-success': flash.type == 'notice', 'alert-error': flash.type != 'notice'}"}}
        %a.close{data: {dismiss: 'alert'}, ng: {click: 'clearMessages()'}} x
        %div{id: "flash_{{flash.type}}"} {{flash.message}}

    .content
      = yield
      .ng-view

    %footer#footer
      .navbar.navbar-static-top
        %nav.navbar-inner
          .container
            %ul.nav.pull-left
              %li
                %a{:href=>'/faq', :target=>'_self'} Support
              %li
                %a{:href=>'/terms#privacy', :target=>'_self'} Privacy Policy
              %li
                %a{:href=>'/terms', :target=>'_self'} Terms
            